# Generated by Django 3.2.9 on 2021-12-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rg',
            field=models.IntegerField(),
        ),
    ]
